# Generated by Django 4.0.2 on 2022-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
